server:
  port: 30023
  context-path: /
spring:
  application:
    name: AutoExectue
  datasource:
    url: jdbc:sqlite:ssh.db?journal_mode=WAL&synchronous=NORMAL
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1 #最大连接数,默认值10.

logging:
  level:
    com.magic.ssh: DEBUG
    com.magic.ssh.mapper: DEBUG

# 线程池配置
task:
  async:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 60
    queueCapacity: 50

exec:
  async:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 120
    queueCapacity: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.magic.ssh.entity
  configuration:
    map-underscore-to-camel-case: true


