server:
  port: 30023
  context-path: /
spring:
  application:
    name: AutoExectue
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.magic.ssh: DEBUG
    com.magic.ssh.mapper: DEBUG

# 线程池配置
task:
  async:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 60
    queueCapacity: 50

exec:
  async:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 120
    queueCapacity: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.magic.ssh.entity
  configuration:
    map-underscore-to-camel-case: true